// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/navbar";
// import {  ShoppingCartProvider } from '../components/context/shoppingcartcontext';
// import { Toaster } from "react-hot-toast";
// import getAuthUser from "@/lib/getAuthUser";
// import localFont from "next/font/local";







// // export const geistSans = localFont({
// //   src: "/fonts/GEIST-REGULAR.woff2",
// //   variable: "--font-geist-sans",
// // });

// // export const geistMono = localFont({
// //   src: "/fonts/GEISTMONO-REGULAR.woff2",
// //   variable: "--font-geist-mono",
// // });



// export const geistSans = localFont({
//   src: "/fonts/GEIST-REGULAR.woff2", // starts with /, points to public/fonts
//   variable: "--font-geist-sans",
// });

// export const geistMono = localFont({
//   src: "/fonts/GEISTMONO-REGULAR.woff2",
//   variable: "--font-geist-mono",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// console.log("geistSans src:", geistSans);
// console.log("geistMono src:", geistMono);
// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>)


// {
//  const authUser = await getAuthUser(); // here
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
      
//        <ShoppingCartProvider>
//        <Navbar   authUser ={authUser??undefined}   />
//         {children}
//          <Toaster position="top-right" />
//        </ShoppingCartProvider>
      
//       </body>
//     </html>
//   );
// }








// import type { Metadata } from "next";
// import "./globals.css";
// import Navbar from "@/components/navbar";
// import { ShoppingCartProvider } from "@/components/context/shoppingcartcontext";
// import { Toaster } from "react-hot-toast";
// import getAuthUser from "@/lib/getAuthUser";
// import localFont from "next/font/local";

// export const geistSans = localFont({
//   src: "/fonts/geist-mono.woff2",
//   variable: "--font-geist-sans",
// });

// export const geistMono = localFont({
//   src: "/fonts/geist-regular.woff2",
//   variable: "--font-geist-mono",
// });

/////////////////////////////////////////////////////////

// export const geistSans = localFont({
//   src: "/fonts/geist-regular.woff2", // ✅ CORRECT
//   variable: "--font-geist-sans",
// });

// export const geistMono = localFont({
//   src: "/fonts/geist-mono.woff2", // ✅ CORRECT
//   variable: "--font-geist-mono",
// });




// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   const authUser = await getAuthUser();

//   return (
//     <html lang="en">
//       {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ShoppingCartProvider>
//           <Navbar authUser={authUser ?? undefined} />
//           {children}
//           <Toaster position="top-right" />
//         </ShoppingCartProvider>
//       </body>
//     </html>
//   );
// }




import "@fontsource/geist-sans/400.css";
import "@fontsource/geist-mono/400.css";

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ShoppingCartProvider } from "@/components/context/shoppingcartcontext";
import { Toaster } from "react-hot-toast";
import getAuthUser from "@/lib/getAuthUser";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const authUser = await getAuthUser();

  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <ShoppingCartProvider>
          <Navbar authUser={authUser ?? undefined} />
          {children}
          <Toaster position="top-right" />
        </ShoppingCartProvider>
      </body>
    </html>
  );
}
