import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import {  ShoppingCartProvider } from '../components/context/shoppingcartcontext';
import { Toaster } from "react-hot-toast";
import getAuthUser from "@/lib/getAuthUser";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{
 const authUser = await getAuthUser(); // here
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
       <ShoppingCartProvider>
       <Navbar   authUser ={authUser}   />
        {children}
         <Toaster position="top-right" />
       </ShoppingCartProvider>
      
      </body>
    </html>
  );
}








